name: poison
#description: xxx
environment:
#  sdk: '>=3.3.0'
#sdk: '>=3.4.1'
#  sdk: '>=3.4.1'
  sdk: '^3.5.0-152'

#  sdk: '>=3.0.0'
#  下面把dart sdk改成3.0以下的版本
#  sdk: '>=2.10.0 <3.0.0'
  #2.12版本以后支持空安全
#  sdk: '>=2.12.0'
#  sdk: '>=2.0.0'
#  flutter:
#
#
#
dependencies:
  #071 time第三方库使用
  http: ^1.2.2
  json: ^0.20.2
  time: "^2.1.3"

